name: algorand_dart
description: Unofficial community SDK to interact with the Algorand network, for Dart & Flutter
version: 2.0.0-dev.5
homepage: https://www.algorand.com
repository: https://github.com/RootSoft/algorand-dart
issue_tracker: https://github.com/RootSoft/algorand-dart/issues

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  # Ed25519
  cryptography: ^2.0.5

  # SHA512/256
  crypto: ^3.0.2

  # Base32
  base32: ^2.1.3

  # Convert
  convert: ^3.0.2

  # Easily work with bytes
  buffer: ^1.1.1

  # Equatable
  equatable: ^2.0.3

  # JSON Annotation
  json_annotation: ^4.7.0

  # Equality
  collection: ^1.15.0

  # HTTP & REST
  dio: ^4.0.6
  retrofit: ^3.3.1

  # Messagepack
  msgpack_dart: ^1.0.0

  # Key Management Daemon API
  algorand_kmd: ^1.0.0

  built_value: '>=8.0.4 <9.0.0'
  built_collection: '>=5.0.0 <6.0.0'

dev_dependencies:
  # Testing framework
  test: ^1.21.3

  # Build Runner & Source Generation
  build_runner: '>2.3.0 <4.0.0'

  # Linter
  pedantic: ^1.11.0

  # JSON Serialization
  json_serializable: ^6.5.4

  # Retrofit
  retrofit_generator: ^4.2.0