name: algorand_dart
description: Unofficial community SDK to interact with the Algorand network, for Dart & Flutter
version: 2.0.0-dev.10
homepage: https://www.algorand.com
repository: https://github.com/RootSoft/algorand-dart
issue_tracker: https://github.com/RootSoft/algorand-dart/issues

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  # Ed25519
  cryptography: ^2.5.0

  # SHA512/256
  crypto: ^3.0.2

  # Base32
  base32: ^2.1.3

  # Convert
  convert: ^3.1.1

  # Easily work with bytes
  buffer: ^1.2.0

  # Equatable
  equatable: ^2.0.5

  # JSON Annotation
  json_annotation: ^4.8.0

  # Equality
  collection: ^1.17.0

  # HTTP & REST
  dio: ^4.0.6
  retrofit: ^3.3.1

  # Messagepack
  algorand_msgpack: ^1.0.1

  algorand_json: ^0.0.1

dev_dependencies:
  # Testing framework
  test: ^1.23.1

  # Build Runner & Source Generation
  build_runner: '>2.3.0 <4.0.0'

  # Linter
  pedantic: ^1.11.0

  # JSON Serialization
  json_serializable: ^6.6.1

  # Retrofit
  retrofit_generator: ^4.2.0